const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.shadowlight,
		C3.Plugins.iframe,
		C3.Plugins.Json,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Acts.MoveForward,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{Fish: 0},
	{Touch: 0},
	{Dest: 0},
	{ShadowCaster: 0},
	{Cursor: 0},
	{Fishcount: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{ShadowLight: 0},
	{Hp: 0},
	{BigGoldFish: 0},
	{iframe: 0},
	{Att2: 0},
	{Pregress: 0},
	{Sprite4: 0},
	{T2hookfrfr: 0},
	{T3rod: 0},
	{Goldfishupgrade: 0},
	{Sprite5: 0},
	{TiledBackground2: 0},
	{Save: 0},
	{JSON: 0},
	{LocalStorage: 0},
	{Load: 0},
	{Rod: 0},
	{Bigoldfish: 0},
	{Goldfchance: 0}
];

self.InstanceType = {
	Fish: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Dest: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Fishcount: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	BigGoldFish: class extends self.ISpriteInstance {},
	iframe: class extends self.IIframeInstance {},
	Att2: class extends self.ITextInstance {},
	Pregress: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	T2hookfrfr: class extends self.ITextInstance {},
	T3rod: class extends self.ITextInstance {},
	Goldfishupgrade: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Save: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	Load: class extends self.ISpriteInstance {}
}